version: "3"
services:

  devstack:
    image: tianon/true
    restart: "no"
    depends_on:
      - devstack_tools
      - devstack_app_deps

  devstack_app_deps:
    image: tianon/true
    restart: "no"
    depends_on:
      - mongodb

  devstack_tools:
    image: tianon/true
    restart: "no"
    depends_on: []

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env

volumes:
  mongo_data:
